baseURL = "https://hd10.dev/"
languageCode = "en-us"
title = "Hemil Desai"
theme = "ink"
paginate = 5

copyright = "© Hemil Desai"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses=true

googleAnalytics = "UA-123-45"
disqusShortname = "hemil10"

[params]
	subtitle = "Thoughts on Artificial Intelligence and Machine Learning"

	# Optional 64x64 avatar image.
	# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true
	favicon = "true"

	mode = "auto" # "dark" or "auto"
	customCSS = "css/syntax.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hemildesai"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hemildesai10"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/hemildesai"

[[params.social]]
name = "Resume"
icon = "file-text"
url = "https://drive.google.com/file/d/0B-GDWDGrOAVzXzdMY0FfN3N5YTlpRkJqRzZmaGNYeVcxNFNr/view"

[taxonomies]
   tag = "tags"