[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_BASEURL = "/"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
